apiVersion: v1
kind: Service
metadata: 
  name: service-cluster
  namespace: default
spec:
  selector:
    app: headless
  type: ClusterIP
  clusterIP: 10.96.0.100
  ports:
  - name: http
    port: 80
    protocol: TCP